trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Set up Python environment.
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

# Step 2: Install dependencies.
- script: |
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Build step (placeholder).
- script: |
    echo "Building project..."
  displayName: 'Build'

# Step 4: Generate an input file for analysis (for demonstration).
- script: |
    echo "def concurrent_function():" > code_to_analyze.txt
    echo "    # Simulate a concurrency issue: shared mutable state" >> code_to_analyze.txt
    echo "    shared = []" >> code_to_analyze.txt
    echo "    for i in range(10):" >> code_to_analyze.txt
    echo "        shared.append(i)" >> code_to_analyze.txt
    echo "    return shared" >> code_to_analyze.txt
  displayName: 'Generate Sample Input File'

# Step 5: Run AI Analysis step.
- script: |
    python ai_analysis.py --input code_to_analyze.txt
  displayName: 'Run AI Analysis'
  env:
    AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
    AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
    AZURE_OPENAI_API_VERSION: $(AZURE_OPENAI_API_VERSION)
    AZURE_OPENAI_DEPLOYMENT_NAME: $(AZURE_OPENAI_DEPLOYMENT_NAME)

# Step 6: Publish the revised code as an artifact.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/revised_code.py'
    ArtifactName: 'revised_code'
    publishLocation: 'Container'
  displayName: 'Publish Revised Code Artifact'
